version: '3.9'
services:
  #Servicio para NodeJS
  app:
    container_name: t2-profile
    build: . 
    env_file: ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - './:/usr/src/app'
    expose:
      - 3001

  # Servicio para PostgreSQL
  postgres:
    image: postgres:latest
    env_file: ./.env
    container_name: t2-profile-db
    environment:
      POSTGRES_DB: profile
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Servicio para PgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ./.env
    container_name: t2-profile-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  prisma-postgres-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t2-profile-prisma
    depends_on:
      - postgres
      - app
    ports:
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    entrypoint: ["bash", "-c", "sleep 10 && npx prisma migrate dev --name init"]
    restart: "no"

volumes:    
  postgres-data:
  pgadmin-data: