version: '3.9'
services:
  #Servicio para NodeJS
  t2-profile:
    container_name: t2-profile
    build: . 
    env_file: ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - './:/usr/src/app'
    networks:
      - taller2

  # Servicio para PostgreSQL
  t2-profile-db:
    image: postgres:latest
    env_file: ./.env
    container_name: profile-db
    environment:
      POSTGRES_DB: profile
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taller2

  # Servicio para PgAdmin
  t2-profile-pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ./.env
    container_name: t2-profile-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - t2-profile-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - taller2
  
  t2-profile-prisma:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t2-profile-prisma
    depends_on:
      - t2-profile-db
      - t2-profile
    ports:
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    entrypoint: ["bash", "-c", "sleep 10 && npx prisma migrate dev --name init"]
    restart: "no"
    networks:
      - taller2

volumes:    
  postgres-data:
  pgadmin-data:

networks:
  taller2:
    external: true