version: '3.9'
services:
  #Servicio para NodeJS
  t2-profile:
    container_name: t2-profile
    build: . 
    ports:
      - 3001:3001
    links:
      - t2-profile-db
    depends_on:
      - t2-profile-db
    networks:
      - taller2

  # Servicio para PostgreSQL
  t2-profile-db:
    image: postgres:latest
    container_name: profile-db
    environment:
      POSTGRES_DB: profile
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5433
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taller2

  # Servicio para PgAdmin
  t2-profile-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: t2-profile-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5052:80
    depends_on:
      - t2-profile-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - taller2
  
  t2-profile-prisma:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t2-profile-prisma
    depends_on:
      - t2-profile-db
      - t2-profile
    ports:
      - "5053:5053"
    entrypoint: ["bash", "-c", "npx prisma migrate dev --name init"]
    restart: "no"
    networks:
      - taller2

volumes:    
  postgres-data:
  pgadmin-data:

networks:
  taller2:
    external: true